# server
server:
  port: 8080
  context-path: /assist-geo

spring:
  # datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/rocket-demo?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource

  freemarker:
    template-loader-path: classpath:/templates/
    request-context-attribute: rc
    suffix: .ftl
    cache: false

  mvc:
    static-path-pattern: /static/**

  devtools:
    restart:
      additional-paths: rocket-demo/src/main

  redis:
    database: 0
    host: 10.11.160.102
    port: 6379
    password:
    pool:
      max-active: 8


# mybatis
mybatis-plus:
  mapper-locations: classpath:cn/swipeblade/assistgeo/rockdemo/mapper/xml/*Mapper.xml
  typeAliasesPackage: cn.swipeblade.assistgeo.rockdemo.entity